### PR TITLE
up2-leds sample built in c added

### PR DESCRIPTION
**Pull request by andrey4latyshev**
LEDs sample (available only on Up Squared) was converted to C

### CODE REVIEW

**Comment by Propanu** [comment]
Hi @andrey4latyshev did you check this against MRAA 1.9 or latest? There were some API updates around named LED devices that might have to be taken into consideration for the new MRAA 2.0 release.

**Comment by andrey4latyshev** [comment]
Hi @Propanu 
I have tested this code on MRAA 1.9 and it was OK. Should I add some if-statements to take into account the version of MRAA or would it be better to do this after the MRAA-release?

**Comment by Propanu** [comment]
Let's do a quick test and confirm it still works after I tag MRAA 2.0 later today. Thanks!

**Comment by sasmita** [comment]
LGTM, but let's wait on Tudor to confirm if it works fine with MRAA 2.0

**Comment by anjgola** [comment]
When done, should be merged to update 1 since we missed the gold QA. I just created a branch.

**Comment by anjgola** [comment]
Merging this. Please file a new JIRA for update 1.

**Comment by anjgola** [comment]
*for 2.0

**Pull request merged**
