### PR TITLE
Iss 2039

### PR DESCRIPTION
**Pull request by vsorokin11**

### CODE REVIEW

**Comment by anjgola** [comment]
I did not predict that the path of the README file will be different for all the branches. 

@johnkhines Please look at the last two commits in this PR. By adding README url to all the sample.json we will need to make sure we are making the right path for right branch. This seems like a lot of overhead to me. We will have to do a manual update on all release branches and then it will essentially be a forever conflict. Not to mention one additional thing to do in every PR.
Would it be instead better to auto-create this URL/path in the aggregator script that the README of a sample is expected to be at '<samplepath>README.md.

We could choose to stick to the README.md at master which is what @vsorokin11  has done right now but I don't know if that is great usability. @vsorokin11 Please create your branch with not master as base but iss2019-beta as base.

**Comment by anjgola** [comment]
@vsorokin11  I rebased the branch from beta. We make changes to master when a product release gets promoted to 'Gold'.

**Comment by johnkhines** [comment]
@anjgola The samples aggregator has the current branch name easily accessible. Would it be more maintainable for it to do a replace on the sample_readme_uri?
For example, a sample.json on the iss2018-update1 could look like this:
    "sample_readme_uri": "https://github.com/intel-iot-devkit/iot-devkit-samples/blob/$BRANCHNAME/aws-pub-sub/cpp/README.md",
And be converted to:
    "sample_readme_uri": "https://github.com/intel-iot-devkit/iot-devkit-samples/blob/iss2018-update1/aws-pub-sub/cpp/README.md",

This would allow you to have different README.md locations per sample per branch.

**Comment by anjgola** [comment]
@johnkhines  Sorry I missed that comment of yours. I like that alternative more!

@VadimPopov  Let us go for the solution that John is proposing. We will not be merging this PR but instead changing the requirements for the JIRA and re-assigning it to someone who can work on the aggregator scripts. Are you interested in that? It is a github.intel.com repo and we can get you access.

**Comment by anjgola** [comment]
I am closing this PR without merge as we will do the proposed automated solution. Please see ISS-2039 for details.

**Pull request closed without merging**
